// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: V1/Users/services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Shoc.Identity.Proto.V1.Users {

  /// <summary>Holder for reflection information generated from V1/Users/services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for V1/Users/services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdWMS9Vc2Vycy9zZXJ2aWNlcy5wcm90bxIIdjEudXNlcnMaF1YxL1VzZXJz",
            "L21lc3NhZ2VzLnByb3RvMksKC1VzZXJTZXJ2aWNlEjwKB0dldEJ5SWQSHC52",
            "MS51c2Vycy5HZXRVc2VyQnlJZFJlcXVlc3QaEy52MS51c2Vycy5Vc2VyTW9k",
            "ZWxCH6oCHFNob2MuSWRlbnRpdHkuUHJvdG8uVjEuVXNlcnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Shoc.Identity.Proto.V1.Users.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
