#!/bin/bash

SERVER=${SHOC_REGISTRY_SERVER}
USERNAME=${SHOC_REGISTRY_USERNAME}
PASSWORD=${SHOC_REGISTRY_PASSWORD}
EMAIL=${SHOC_REGISTRY_EMAIL}

AUTH_ENCODED=$(echo "$USERNAME:$PASSWORD" | base64 | tr -d '\n')
CONFIG_PLAIN=$(echo "{\"$SERVER\":{\"USERNAME\":\"$USERNAME\",\"PASSWORD\":\"$PASSWORD\",\"EMAIL\":\"$EMAIL\",\"auth\":\"$AUTH_ENCODED\"}}")
CONFIG_ENCODED=$(echo $CONFIG_PLAIN | base64 | tr -d '\n')

echo $CONFIG_ENCODED
