CREATE TABLE `pkg_packages` (
    `Id` varchar(100) NOT NULL,
    `WorkspaceId` varchar(100) NOT NULL,
    `UserId` varchar(100) NOT NULL,
    `Scope` varchar(64) NOT NULL,
    `ListingChecksum` varchar(256) NOT NULL,
    `Manifest` longtext NOT NULL,
    `Runtime` longtext NOT NULL,
    `Dockerfile` longtext NOT NULL,
    `TemplateReference` text NOT NULL,
    `RegistryId` varchar(100) NOT NULL,
    `Image` text NOT NULL,
    `Created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`),
    KEY `FK_Packages_Workspaces_idx` (`WorkspaceId`),
    KEY `FK_Packages_Users_idx` (`UserId`),
    KEY `FK_Packages_Registry_idx` (`RegistryId`),
    KEY `IDX_ListingChecksum` (`ListingChecksum`),
    CONSTRAINT `FK_Packages_Registry` FOREIGN KEY (`RegistryId`) REFERENCES `reg_registries` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_Packages_Users` FOREIGN KEY (`UserId`) REFERENCES `idp_users` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_Packages_Workspaces` FOREIGN KEY (`WorkspaceId`) REFERENCES `wspc_workspaces` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pkg_build_tasks` (
    `Id` varchar(100) NOT NULL,
    `WorkspaceId` varchar(100) NOT NULL,
    `UserId` varchar(100) NOT NULL,
    `Provider` varchar(64) NOT NULL,
    `Scope` varchar(64) NOT NULL,
    `ListingChecksum` varchar(256) NOT NULL,
    `Manifest` longtext NOT NULL,
    `Runtime` longtext NOT NULL,
    `Dockerfile` longtext NOT NULL,
    `TemplateReference` text NOT NULL,
    `RegistryId` varchar(100) NOT NULL,
    `Status` varchar(64) NOT NULL,
    `Deadline` datetime DEFAULT NULL,
    `PackageId` varchar(100) DEFAULT NULL,
    `ErrorCode` text,
    `Created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`),
    KEY `FK_BuildTasks_Workspaces_idx` (`WorkspaceId`),
    KEY `FK_BuildTasks_Users_idx` (`UserId`),
    KEY `FK_BuildTasks_Packages_idx` (`PackageId`),
    KEY `FK_BuildTasks_Registries_idx` (`RegistryId`),
    CONSTRAINT `FK_BuildTasks_Packages` FOREIGN KEY (`PackageId`) REFERENCES `pkg_packages` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_BuildTasks_Registries` FOREIGN KEY (`RegistryId`) REFERENCES `reg_registries` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_BuildTasks_Users` FOREIGN KEY (`UserId`) REFERENCES `idp_users` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_BuildTasks_Workspaces` FOREIGN KEY (`WorkspaceId`) REFERENCES `wspc_workspaces` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
